### ISSUE TITLE
Help setting up volumes to access data

### ISSUE THREAD

**Issue by OnTheRicky** [kubeflow-kale/kale#107]
I have Kale in a custom notebook image on kubeflow and not using miniKF/Rok.
There is no documentation, so I'm a little stuck on how to set things up so I can run a pipeline that can access data?

**Comment by StefanoFioravanzo** [comment]
Hi @OnTheRicky , in order to access data in our pipeline steps you need to mounts a pvc in the pipelines steps. Have you tried using the Volumes form of the Kale panel to mount a PVC that contains our data? 

Can tell me what you have tried and what went wrong?

**Comment by yaliqin** [comment]
I met the same problem. What to file in the mount point field? I setup a nfs server by myself. should I fill this field with the nfs server data directory? I did it. And the pipeline run failed in the load data step. The error message is 
"Traceback (most recent call last):
  File "<string>", line 63, in <module>
  File "<string>", line 16, in loaddata
  File "/usr/local/lib/python3.6/dist-packages/kubeflow_kale-0.3.4-py3.6.egg/kale/utils/pod_utils.py", line 186, in snapshot_pipeline_step
    rok = RokClient()
  File "build/bdist.linux-x86_64/egg/rok_gw_client/client.py", line 163, in __init__
ValueError: A Rok API URL must be provided either via the `url' argument or the `ROK_GW_URL' environment variable."

**Comment by yaliqin** [comment]
I met the same problem. What should fill in the "mount point" field in Kale Deployment Panel if I want to add a new volume? I setup a nfs server by myself. should I fill this field with the nfs server data directory? I did it. And the pipeline run failed in the load data step. The error message is
"Traceback (most recent call last):
File "", line 63, in
File "", line 16, in loaddata
File "/usr/local/lib/python3.6/dist-packages/kubeflow_kale-0.3.4-py3.6.egg/kale/utils/pod_utils.py", line 186, in snapshot_pipeline_step
rok = RokClient()
File "build/bdist.linux-x86_64/egg/rok_gw_client/client.py", line 163, in init
ValueError: A Rok API URL must be provided either via the url' argument or the ROK_GW_URL' environment variable."

**Comment by rmguy** [comment]
Hey @StefanoFioravanzo, same issue here. I tried using the volumes form of the kale panel for both reusing existing volumes and creating new ones, without any luck. The workload pods of the pipeline show up without the specified volumes. Any debug pointers? Btw any way I can deploy rok by hand? (On prem, no vagrant allowed because of security risks)
