### ISSUE TITLE
Failed to collect metrics from worker container

### ISSUE THREAD

**Issue by jazzsir** [kubeflow-kale/kale#188]
To run dog-breed-classification
 
1) Created Notebook Server with gcr.io/arrikto/jupyter-kale:v0.5.0
2) Replaced images with..
  - Katib controller: gcr.io/arrikto/katib-controller:40b5b51a
  - Katib Chocolate service: gcr.io/arrikto/suggestion-chocolate:40b5b51a

as described on [Hands-On](https://medium.com/kubeflow/kubeflow-kale-simplify-building-better-ml-pipelines-with-automatic-hyperparameter-tuning-5821747f4fcb) .

But, metrics-logger-and-collector can't collect metrics with an error

```
kubeflow@hbseo-m:~$ kubectl -n admin get po
NAME                                          READY   STATUS    RESTARTS   AGE
dog-breed-katib-p01pk-6487aa2c-qwht7          2/2     Running   0          7s
dog-breed-katib-p01pk-grid-656f7c4459-5w5gs   1/1     Running   0          47s
test99-0                                      2/2     Running   0          7m12s
kubeflow@hbseo-m:~$ 
kubeflow@hbseo-m:~$ kubectl -n admin logs -f dog-breed-katib-p01pk-6487aa2c-qwht7 -c metrics-logger-and-collector
I0827 02:46:30.537116      12 main.go:85] Trial Name: dog-breed-katib-p01pk-6487aa2c
I0827 02:46:32.817593      12 main.go:79] 2020-08-27T02:46:32Z kfp_utils:315 [INFO] Watching for Run with ID: '9af2e79b-ef0d-423f-98d1-cc93d7d7f903' in namespace 'kubeflow'
I0827 02:47:02.904638      12 main.go:79] 2020-08-27T02:47:02Z kfp_utils:322 [INFO] Run status: Failed
I0827 02:47:02.904673      12 main.go:79] 2020-08-27T02:47:02Z kfp_utils:387 [WARNING] KFP run did not run successfully. No metrics to return.
F0827 02:47:03.538149      12 main.go:95] Failed to wait for worker container: Process 6 hadn't completed: open /var/log/katib/6.pid: no such file or directory
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc00019e100, 0xc00023c000, 0xa0, 0x1d6)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb8
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0x129da40, 0xc000000003, 0xc000181030, 0x12378d6, 0x7, 0x5f, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2d0
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0x129da40, 0x3, 0xc78f77, 0x27, 0xc00015fed8, 0x1, 0x1)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
        /go/src/github.com/kubeflow/katib/cmd/metricscollector/v1alpha3/file-metricscollector/main.go:95 +0x279

```

kubeflow: kfctl_k8s_istio.v1.0.2
kubernetes: v1.17.11
OS: Ubuntu 18.04.4 LTS

**Comment by StefanoFioravanzo** [comment]
@jazzsir  Apparently the corresponding pipeline run is failing, as you can see in the corresponding logs:

```
I0827 02:46:32.817593      12 main.go:79] 2020-08-27T02:46:32Z kfp_utils:315 [INFO] Watching for Run with ID: '9af2e79b-ef0d-423f-98d1-cc93d7d7f903' in namespace 'kubeflow'
I0827 02:47:02.904638      12 main.go:79] 2020-08-27T02:47:02Z kfp_utils:322 [INFO] Run status: Failed
I0827 02:47:02.904673      12 main.go:79] 2020-08-27T02:47:02Z kfp_utils:387 [WARNING] KFP run did not run successfully. No metrics to return.
```

Can you please check the state of the pipeline run, and see why it is failing?

**Comment by jazzsir** [comment]
@StefanoFioravanzo Thanks, I recognized some libraries need to be installed.
Unfortunately, I don't use Rok, so I copied all dataset into the container image using Dockerfile, and changed path of the dataset in `dog-breed-katib.ipynb` file.
But, some errors occur in pipeline container as below.

```
host@hbseo-m:~/go/src/github.com/kubeflow/kale$ kubectl -nkubeflow logs -f dog-breed-qhn9k-kl4vt-716778710 -cmain
03:26:24 Kale marshalling [INFO] Loading general object: /marshal/dog_names.dillpkl
03:26:24 Kale marshalling [INFO] Loading function: path_to_tensor.pyfn
03:26:24 Kale marshalling [INFO] Loading numpy obj: test_files.npy
03:26:24 Kale marshalling [INFO] Loading numpy obj: test_targets.npy
03:26:24 Kale marshalling [INFO] Loading numpy obj: train_targets.npy
03:26:24 Kale marshalling [INFO] Loading numpy obj: valid_targets.npy
2020-08-28 03:26:26.704288: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-28 03:26:26.704338: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-28 03:26:26.704365: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dog-breed-qhn9k-kl4vt-716778710): /proc/driver/nvidia/version does not exist
2020-08-28 03:26:26.704620: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-28 03:26:26.712710: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-08-28 03:26:26.713374: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe38c000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-28 03:26:26.713406: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
flatten (Flatten)            (None, 2048)              0
_________________________________________________________________
dense (Dense)                (None, 256)               524544
_________________________________________________________________
dense_1 (Dense)              (None, 133)               34181
=================================================================
Total params: 558,725
Trainable params: 558,725
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
190/209 [==========================>...] - ETA: 0s - loss: 2.0025 - accuracy: 0.5400
Epoch 00001: val_loss improved from inf to 0.91779, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 4ms/step - loss: 1.9053 - accuracy: 0.5576 - val_loss: 0.9178 - val_accuracy: 0.7186
Epoch 2/20
207/209 [============================>.] - ETA: 0s - loss: 0.4838 - accuracy: 0.8530
Epoch 00002: val_loss improved from 0.91779 to 0.77369, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.4822 - accuracy: 0.8536 - val_loss: 0.7737 - val_accuracy: 0.7677
Epoch 3/20
207/209 [============================>.] - ETA: 0s - loss: 0.2653 - accuracy: 0.9189
Epoch 00003: val_loss improved from 0.77369 to 0.76555, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.2655 - accuracy: 0.9190 - val_loss: 0.7656 - val_accuracy: 0.7796
Epoch 4/20
209/209 [==============================] - ETA: 0s - loss: 0.1611 - accuracy: 0.9531
Epoch 00004: val_loss improved from 0.76555 to 0.66085, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.1611 - accuracy: 0.9531 - val_loss: 0.6609 - val_accuracy: 0.7988
Epoch 5/20
194/209 [==========================>...] - ETA: 0s - loss: 0.0948 - accuracy: 0.9774
Epoch 00005: val_loss did not improve from 0.66085
209/209 [==============================] - 1s 3ms/step - loss: 0.0984 - accuracy: 0.9762 - val_loss: 0.7250 - val_accuracy: 0.7904
Epoch 6/20
196/209 [===========================>..] - ETA: 0s - loss: 0.0722 - accuracy: 0.9837
Epoch 00006: val_loss improved from 0.66085 to 0.65426, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.0724 - accuracy: 0.9840 - val_loss: 0.6543 - val_accuracy: 0.8024
Epoch 7/20
197/209 [===========================>..] - ETA: 0s - loss: 0.0371 - accuracy: 0.9952
Epoch 00007: val_loss improved from 0.65426 to 0.63860, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.0389 - accuracy: 0.9946 - val_loss: 0.6386 - val_accuracy: 0.8168
Epoch 8/20
198/209 [===========================>..] - ETA: 0s - loss: 0.0328 - accuracy: 0.9948
Epoch 00008: val_loss improved from 0.63860 to 0.59682, saving model to saved_models/weights.best.ResNet50.hdf5
209/209 [==============================] - 1s 3ms/step - loss: 0.0319 - accuracy: 0.9951 - val_loss: 0.5968 - val_accuracy: 0.8311
Epoch 9/20
195/209 [==========================>...] - ETA: 0s - loss: 0.0263 - accuracy: 0.9955
Epoch 00009: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0265 - accuracy: 0.9954 - val_loss: 0.6125 - val_accuracy: 0.8251
Epoch 10/20
204/209 [============================>.] - ETA: 0s - loss: 0.0370 - accuracy: 0.9920
Epoch 00010: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0371 - accuracy: 0.9921 - val_loss: 0.7206 - val_accuracy: 0.8060
Epoch 11/20
191/209 [==========================>...] - ETA: 0s - loss: 0.0499 - accuracy: 0.9887
Epoch 00011: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0520 - accuracy: 0.9877 - val_loss: 0.8259 - val_accuracy: 0.8024
Epoch 12/20
207/209 [============================>.] - ETA: 0s - loss: 0.0799 - accuracy: 0.9799
Epoch 00012: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0804 - accuracy: 0.9798 - val_loss: 0.8422 - val_accuracy: 0.7892
Epoch 13/20
202/209 [===========================>..] - ETA: 0s - loss: 0.0863 - accuracy: 0.9763
Epoch 00013: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0869 - accuracy: 0.9757 - val_loss: 0.8585 - val_accuracy: 0.7760
Epoch 14/20
195/209 [==========================>...] - ETA: 0s - loss: 0.0896 - accuracy: 0.9748
Epoch 00014: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0924 - accuracy: 0.9734 - val_loss: 1.0419 - val_accuracy: 0.7701
Epoch 15/20
198/209 [===========================>..] - ETA: 0s - loss: 0.0780 - accuracy: 0.9774
Epoch 00015: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0772 - accuracy: 0.9777 - val_loss: 0.9807 - val_accuracy: 0.7808
Epoch 16/20
193/209 [==========================>...] - ETA: 0s - loss: 0.0442 - accuracy: 0.9870
Epoch 00016: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0467 - accuracy: 0.9862 - val_loss: 0.9451 - val_accuracy: 0.8060
Epoch 17/20
195/209 [==========================>...] - ETA: 0s - loss: 0.0287 - accuracy: 0.9918
Epoch 00017: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0296 - accuracy: 0.9918 - val_loss: 0.8815 - val_accuracy: 0.8024
Epoch 18/20
205/209 [============================>.] - ETA: 0s - loss: 0.0286 - accuracy: 0.9941
Epoch 00018: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0291 - accuracy: 0.9940 - val_loss: 0.8465 - val_accuracy: 0.8216
Epoch 19/20
193/209 [==========================>...] - ETA: 0s - loss: 0.0216 - accuracy: 0.9938
Epoch 00019: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0209 - accuracy: 0.9942 - val_loss: 0.8219 - val_accuracy: 0.8192
Epoch 20/20
204/209 [============================>.] - ETA: 0s - loss: 0.0183 - accuracy: 0.9954
Epoch 00020: val_loss did not improve from 0.59682
209/209 [==============================] - 1s 3ms/step - loss: 0.0182 - accuracy: 0.9954 - val_loss: 0.9093 - val_accuracy: 0.8192
Test accuracy: 81.9378%
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
94773248/94765736 [==============================] - 2s 0us/step
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, 2048) for input Tensor("flatten_input:0", shape=(None, 1, 1, 2048), dtype=float32), but it was called on an input with incompatible shape (None, 7, 7, 2048).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-c706ab07d5b2> in <module>
     36 gtruth = np.argmax(test_targets[0])
     37 gtruth = dog_names[gtruth].split('.')[-1]
---> 38 pred = predict_breed(img_path)
     39 print("Groundtruth dog breed: {}".format(gtruth))
     40 print("Predicted dog breed: {}".format(pred))

<ipython-input-10-c706ab07d5b2> in predict_breed(img_path)
      2     img = path_to_tensor(img_path)
      3     bottleneck_feature = extract_Resnet50(img)
----> 4     predicted = ResNet50_model.predict(bottleneck_feature)
      5     idx = np.argmax(predicted)
      6     return dog_names[idx].split('.')[-1]

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     86       raise ValueError('{} is not supported in multi-worker mode.'.format(
     87           method.__name__))
---> 88     return method(self, *args, **kwargs)
     89
     90   return tf_decorator.make_decorator(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1266           for step in data_handler.steps():
   1267             callbacks.on_predict_batch_begin(step)
-> 1268             tmp_batch_outputs = predict_function(iterator)
   1269             # Catch OutOfRangeError for Datasets of unknown size.
   1270             # This blocks until the batch has finished executing.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581
    582     if tracing_count == self._get_tracing_count():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    616       # In this case we have not created variables on the first call. So we can
    617       # run the first trace but we should fail if variables are created.
--> 618       results = self._stateful_fn(*args, **kwds)
    619       if self._created_variables:
    620         raise ValueError("Creating variables on a non-first call to a function"

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2417     """Calls a graph function specialized to the inputs."""
   2418     with self._lock:
-> 2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2772           and self.input_signature is None
   2773           and call_context_key in self._function_cache.missed):
-> 2774         return self._define_function_with_shape_relaxation(args, kwargs)
   2775
   2776       self._function_cache.missed.add(call_context_key)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _define_function_with_shape_relaxation(self, args, kwargs)
   2704         relaxed_arg_shapes)
   2705     graph_function = self._create_graph_function(
-> 2706         args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
   2707     self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
   2708

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2665             arg_names=arg_names,
   2666             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2667             capture_by_value=self._capture_by_value),
   2668         self._function_attributes,
   2669         # Tell the ConcreteFunction to clean up its graph once it goes out of

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    439         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    440         # the function a weak reference to itself to avoid a reference cycle.
--> 441         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    442     weak_wrapped_fn = weakref.ref(wrapped_fn)
    443

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1122 predict_step  **
        return self(x, training=False)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:927 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:277 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py:719 call
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py:888 _run_internal_graph
        output_tensors = layer(computed_tensors, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:886 __call__
        self.name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py:216 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer dense is incompatible with the layer: expected axis -1 of input shape to have value 2048 but received input with shape [None, 100352]
```

**Comment by StefanoFioravanzo** [comment]
@jazzsir it looks like the code is failing to validate the shape of the dataset. I would suggest making sure that 

- you are using the correct library versions (see `requirements.txt`)
- the data actually exists at the specified path
