### ISSUE TITLE
Make `rok_gw_client` optional

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow-kale/kale#20]
Currently Kale will fail to execute if `rok_gw_client` is not installed. We should make sure that when this library is not present, ROK integration is disabled.

**Comment by Felihong** [comment]
Hi @StefanoFioravanzo , 
I become sometimes `RunTimeError` when using my attached `Filestore` persistent volume, which is dynamically provisioned by `nfs-client`:
```
Function Call: nb.list_volumes()
Status: 2 (ExecutionError)
Type: "RuntimeError"
Message: Found PVC storage provisioner 'cluster.local/nfs-cp-nfs-client-provisioner'. Only storage provisioner 'rok.arrikto.com' is supported.
```
I can resolve this by simply clicking the `OK` bottom, however it would be great to avoid having such warnings. 

Thanks!

**Comment by StefanoFioravanzo** [comment]
@Felihong Yes, we are currently raising that error when there are volumes not managed by Rok storage class. When we will introduce the support for non-Rok environment, this error will disappear as wel

**Comment by elikatsis** [comment]
We do lazy imports now, so it should be fixed.
Closing the issue, feel free to reopen.

**Comment by gabrielclimb** [comment]
Hi, i'm getting this error as well.
Am i doing something wrong @elikatsis ?

```
2020-08-14 15:18:52 run:83 [DEBUG] [TID=db0aydan38] [] Decoding ctx of RPC function 'rok.check_rok_availability'
2020-08-14 15:18:52 run:95 [DEBUG] [TID=db0aydan38] [] Decoding kwargs of RPC function 'rok.check_rok_availability'
2020-08-14 15:18:52 run:104 [DEBUG] [TID=db0aydan38] [] Importing RPC function 'rok.check_rok_availability'
2020-08-14 15:18:54 run:114 [INFO] [TID=db0aydan38] [] Executing RPC function 'check_rok_availability()'
2020-08-14 15:18:54 rok:119 [ERROR] [TID=db0aydan38] [] Failed to import RokClient
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 117, in check_rok_availability
    rok = _get_client()
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 37, in _get_client
    from rok_gw_client.client import RokClient
ModuleNotFoundError: No module named 'rok_gw_client'
2020-08-14 15:18:54 run:120 [ERROR] [TID=db0aydan38] [] RPC function 'check_rok_availability' raised an RPCError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 117, in check_rok_availability
    rok = _get_client()
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 37, in _get_client
    from rok_gw_client.client import RokClient
ModuleNotFoundError: No module named 'rok_gw_client'```

**Comment by elikatsis** [comment]
@gabrielclimb,
what you've pasted is expected.
What Kale does is that it detects whether Rok is installed in the image and whether it can speak with the Rok service. If any of the checks fails, then it disables those options in the labextension which require Rok (e.g., auto-snapshotting).

It looks like you are using a notebook server image without the `rok_gw_client` module, so it doesn't have Rok installed.
This specific error is expected when you are not using one of our images (either directly or as base image).

However, this shouldn't block the rest of the Kale features. So the module **is optional**, but in the same time it is a dependency for some of the features. Can you verify?

**Comment by gabrielclimb** [comment]
@elikatsis thank you to explain.
I was testing from a new image, but also with new kfp. I will get from kale images.
