### ISSUE TITLE
RPC Permissions Errors - Kubeflow + Kale

### ISSUE THREAD

**Issue by LRSutton** [kubeflow-kale/kale#204]
Running on a local Kubernetes 1.17 cluster (installed using KubeADM)
Kubeflow installed using kfctl v1.1.0-0-g9a3621e / kfctl_k8s_istio.v1.1.0.yaml
Installed Kale with following Dockerfile:

```
FROM gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0

USER root

RUN cd /tmp && git clone https://github.com/kubeflow-kale/kale
RUN cd /tmp/kale/backend && python3 ./setup.py install

RUN pip3 install --upgrade pip
RUN pip3 install kubeflow-kale
RUN jupyter labextension install kubeflow-kale-launcher
RUN jupyter labextension list

RUN chown jovyan -R /home/jovyan

USER 1000
```

The labextension list step output the following:

```
Step 8/10 : RUN jupyter labextension list
 ---> Running in c050c1c7b6a4
   app dir: /usr/local/share/jupyter/lab
        kubeflow-kale-launcher v1.4.0  enabled  OK
```

Launching the Jupyter Notebook results in RPC errors / RBAC issues.

I can navigate through though and attempting to "Compile and Run" a notebook, I get:

```
An RPC Error has occurred
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

Type: RPC

Method: nb.compile_notebook()

Code: 6 (UnhandledError)

Transaction ID: j48hs35tcc

Message: compile_notebook() got an unexpected keyword argument 'auto_snapshot'

Details: You can find more information under /home/jovyan/kale.log
``` 

Kale.log:

```
2020-09-13 21:35:49 run:83 [[DEBUG]] [TID=j48hs35tcc] [] Decoding ctx of RPC function 'nb.compile_notebook'
2020-09-13 21:35:49 run:95 [[DEBUG]] [TID=j48hs35tcc] [/home/jovyan/Untitled.ipynb] Decoding kwargs of RPC function 'nb.compile_notebook'
2020-09-13 21:35:49 run:104 [[DEBUG]] [TID=j48hs35tcc] [/home/jovyan/Untitled.ipynb] Importing RPC function 'nb.compile_notebook'
2020-09-13 21:35:49 run:114 [[INFO]] [TID=j48hs35tcc] [/home/jovyan/Untitled.ipynb] Executing RPC function 'compile_notebook(source_notebook_path=Untitled.ipynb, notebook_metadata_overrides={'experiment': {'name': 'Test Run', 'id': 'new'}, 'experiment_name': 'Test Run', 'pipeline_name': 'test-pipeline', 'pipeline_description': 'First Try Building a Pipeline Using Kale', 'docker_image': 'nexus1.technicalabs.com:8123/kubeflow-images/tensorflow-1.15.2-notebook-gpu-kale:1.0.0', 'volumes': []}, debug=False, auto_snapshot=False)'
2020-09-13 21:35:49 run:125 [[ERROR]] [TID=j48hs35tcc] [/home/jovyan/Untitled.ipynb] RPC function 'compile_notebook' raised an unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kubeflow_kale-0.5.1-py3.6.egg/kale/rpc/run.py", line 116, in run
    result = func(request, **kwargs)
TypeError: compile_notebook() got an unexpected keyword argument 'auto_snapshot'
```

I do not have ROC or any ROC related clients installed, I also had both

-     Use this notebook's volumes: False
-     Take Rok Snapshots before each step: False

I expected that having installed Kale per the instructions here: https://pypi.org/project/kubeflow-kale/0.3.2/

that I should be able to create and run a pipeline from a given notebook.

What RBAC / RPC configurations must be included?

**Comment by elikatsis** [comment]
Hi @LRSutton,

The instructions in your Dockerfile end up installing `kubeflow-kale` from `master` branch, and then they install a deprecated Kale lab extension (`kubeflow-kale-launcher`). The lab extension is called `kubeflow-kale-labextension`. Also, you shouldn't expect `master` and latest release to be compatible.

Instead, you should follow the instructions in the README file of this repository: https://github.com/kubeflow-kale/kale#getting-started (since the last release, 0.5.1, you should install `jupyterlab>=2.0.0`. That's the only difference, we should update the instructions).

**Comment by LRSutton** [comment]
Thank you, Ilias. I appreciate you explaining that and pointing me to the docs.

I changed my Dockerfile to:

```
FROM gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0
USER root
RUN pip3 install --upgrade pip
RUN pip install kubeflow-kale
# install jupyter lab
RUN pip install "jupyterlab<2.0.0"
# install the extension
RUN jupyter labextension install kubeflow-kale-labextension
# verify extension status
RUN jupyter labextension list
RUN chown jovyan -R /home/jovyan
USER 1000
```

(Straight copy and paste pretty much, using a known working GCR image for a base.) 

The image builds and deploys fine, but once again, when accessing the notebook, I get similar RBAC errors. Below is the snippet from the kale.log:

```
2020-09-14 13:52:09 run:83 [[DEBUG]] [TID=0ap04fm825] [] Decoding ctx of RPC function 'rok.check_rok_availability'
2020-09-14 13:52:09 run:95 [[DEBUG]] [TID=0ap04fm825] [] Decoding kwargs of RPC function 'rok.check_rok_availability'
2020-09-14 13:52:09 run:104 [[DEBUG]] [TID=0ap04fm825] [] Importing RPC function 'rok.check_rok_availability'
2020-09-14 13:52:10 run:114 [[INFO]] [TID=0ap04fm825] [] Executing RPC function 'check_rok_availability()'
2020-09-14 13:52:10 rok:119 [[ERROR]] [TID=0ap04fm825] [] Failed to import RokClient
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 117, in check_rok_availability
    rok = _get_client()
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 37, in _get_client
    from rok_gw_client.client import RokClient
ModuleNotFoundError: No module named 'rok_gw_client'
2020-09-14 13:52:10 run:120 [[ERROR]] [TID=0ap04fm825] [] RPC function 'check_rok_availability' raised an RPCError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 117, in check_rok_availability
    rok = _get_client()
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 37, in _get_client
    from rok_gw_client.client import RokClient
ModuleNotFoundError: No module named 'rok_gw_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/run.py", line 116, in run
    result = func(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/rok.py", line 121, in check_rok_availability
    trans_id=request.trans_id)
kale.rpc.errors.RPCNotFoundError
2020-09-14 13:52:11 run:83 [[DEBUG]] [TID=etov8mw9ct] [] Decoding ctx of RPC function 'nb.resume_notebook_path'
2020-09-14 13:52:11 run:95 [[DEBUG]] [TID=etov8mw9ct] [] Decoding kwargs of RPC function 'nb.resume_notebook_path'
2020-09-14 13:52:11 run:104 [[DEBUG]] [TID=etov8mw9ct] [] Importing RPC function 'nb.resume_notebook_path'
2020-09-14 13:52:11 run:114 [[INFO]] [TID=etov8mw9ct] [] Executing RPC function 'resume_notebook_path()'
2020-09-14 13:52:11 run:83 [[DEBUG]] [TID=wc8zsgp7gj] [] Decoding ctx of RPC function 'nb.explore_notebook'
2020-09-14 13:52:11 run:95 [[DEBUG]] [TID=wc8zsgp7gj] [/home/jovyan/Untitled.ipynb] Decoding kwargs of RPC function 'nb.explore_notebook'
2020-09-14 13:52:11 run:104 [[DEBUG]] [TID=wc8zsgp7gj] [/home/jovyan/Untitled.ipynb] Importing RPC function 'nb.explore_notebook'
2020-09-14 13:52:11 run:114 [[INFO]] [TID=wc8zsgp7gj] [/home/jovyan/Untitled.ipynb] Executing RPC function 'explore_notebook(source_notebook_path=Untitled.ipynb)'
2020-09-14 13:52:11 run:83 [[DEBUG]] [TID=yg2j77s8q4] [] Decoding ctx of RPC function 'nb.get_base_image'
2020-09-14 13:52:11 run:95 [[DEBUG]] [TID=yg2j77s8q4] [/home/jovyan/Untitled.ipynb] Decoding kwargs of RPC function 'nb.get_base_image'
2020-09-14 13:52:11 run:104 [[DEBUG]] [TID=yg2j77s8q4] [/home/jovyan/Untitled.ipynb] Importing RPC function 'nb.get_base_image'
2020-09-14 13:52:11 run:114 [[INFO]] [TID=yg2j77s8q4] [/home/jovyan/Untitled.ipynb] Executing RPC function 'get_base_image()'
2020-09-14 13:52:11 run:83 [[DEBUG]] [TID=fbpf5ouzs4] [] Decoding ctx of RPC function 'kfp.list_experiments'
2020-09-14 13:52:11 run:95 [[DEBUG]] [TID=fbpf5ouzs4] [/home/jovyan/Untitled.ipynb] Decoding kwargs of RPC function 'kfp.list_experiments'
2020-09-14 13:52:11 run:104 [[DEBUG]] [TID=fbpf5ouzs4] [/home/jovyan/Untitled.ipynb] Importing RPC function 'kfp.list_experiments'
2020-09-14 13:52:11 run:114 [[INFO]] [TID=fbpf5ouzs4] [/home/jovyan/Untitled.ipynb] Executing RPC function 'list_experiments()'
2020-09-14 13:52:11 run:125 [[ERROR]] [TID=fbpf5ouzs4] [/home/jovyan/Untitled.ipynb] RPC function 'list_experiments' raised an unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/run.py", line 116, in run
    result = func(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/kfp.py", line 37, in list_experiments
    for e in c.list_experiments().experiments or []]
  File "/usr/local/lib/python3.6/dist-packages/kfp/_client.py", line 335, in list_experiments
    resource_reference_key_id=namespace)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/experiment_service_api.py", line 581, in list_experiment
    return self.list_experiment_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/experiment_service_api.py", line 696, in list_experiment_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 383, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 202, in __call_api
    raise e
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 199, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 407, in request
    headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 248, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 14 Sep 2020 13:52:11 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied
```

Any continued thoughts on what I might be still doing wrong?

**Comment by elikatsis** [comment]
It looks like you've deployed Multi-User KFP. Unfortunately, we are not aware of an open source deployment configuration that enables the usage of KFP client (there are multiple open issues in the KFP repo).
Even if you overcome the (Istio) RBAC issue you are bumping into, you won't be able to get properly authenticated and authorized.

We, as Arrikto, have made some modifications and support it, but that's for our Enterprise deployments.

**Comment by LRSutton** [comment]
Aah, ok ... I'll need to go figure out how to deploy single-user KFP... That's a good mention that you may want to include in the README... Thanks again Ilias!

**Comment by DavidSpek** [comment]
For reference to others that find this bug report, I believe this bug report is relevant to this issue. 
https://github.com/kubeflow/pipelines/issues/4377

**Comment by DavidSpek** [comment]
Following the comment by yhwang, I was able to get Kale to create and upload a pipeline. https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687689294

For the default `admin@kubeflow.org` user in the `admin` namespce I used this for the servicerolebinding:

```
cat <<EOF | kubectl apply -f -
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-ml-pipeline-nb-admin
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: ml-pipeline-services
  subjects:
  - properties:
      source.principal: cluster.local/ns/admin/sa/default-editor
EOF
```

And this for the envoy filter:

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-header
  namespace: admin
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: ml-pipeline.kubeflow.svc.cluster.local:8888
          route:
            name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: true
          header:
            key: kubeflow-userid
            value: admin@kubeflow.org
  workloadSelector:
    labels:
      notebook-name: mzquality
EOF

**Comment by elikatsis** [comment]
@DavidSpek,

We don't do this exactly. You are actually forcing an identity to your requests which tricks the pods into impersonating you essentially. However, each pod has its own identity and it is this identity what needs to be passed [in a secure way] and parsed by the KFP API server.
We are actually deploying some extra resources in the namespace for this to happen, apart from extending the API server.

**Comment by mr-yaky** [comment]
> Following the comment by yhwang, I was able to get Kale to create and upload a pipeline. [kubeflow/pipelines#4440 (comment)](https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687689294)
> 
> For the default `admin@kubeflow.org` user in the `admin` namespce I used this for the servicerolebinding:
> 
> ```
> cat <<EOF | kubectl apply -f -
> apiVersion: rbac.istio.io/v1alpha1
> kind: ServiceRoleBinding
> metadata:
>   name: bind-ml-pipeline-nb-admin
>   namespace: kubeflow
> spec:
>   roleRef:
>     kind: ServiceRole
>     name: ml-pipeline-services
>   subjects:
>   - properties:
>       source.principal: cluster.local/ns/admin/sa/default-editor
> EOF
> ```
> 
> And this for the envoy filter:
> 
> ```
> cat <<EOF | kubectl apply -f -
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: add-header
>   namespace: admin
> spec:
>   configPatches:
>   - applyTo: VIRTUAL_HOST
>     match:
>       context: SIDECAR_OUTBOUND
>       routeConfiguration:
>         vhost:
>           name: ml-pipeline.kubeflow.svc.cluster.local:8888
>           route:
>             name: default
>     patch:
>       operation: MERGE
>       value:
>         request_headers_to_add:
>         - append: true
>           header:
>             key: kubeflow-userid
>             value: admin@kubeflow.org
>   workloadSelector:
>     labels:
>       notebook-name: mzquality
> EOF
> ```
> 
> EDIT
> 
> This actually seems to be similar to the setup @elikatsis mentioned Arrikto uses for their Kubeflow Enterprise deployments.
> 
> https://docs.arrikto.com/integrations/kubeflow.html#set-up-namespaces

I tried to use that workaround but seems it doesn't works for me. Maybe because I'm testing with anonymous@kubeflow.org and not admin@kubeflow.org. I have set exactly anonymous@kubeflow.org in EnvoyFilter yaml.

**Comment by DavidSpek** [comment]
@mr-yaky Can you post the exact rolebinding and envoyfilter you have used? Also, what namespace does the notebook run in and what is the account that is used (I'm not sure how that is setup in single-user mode).

**Comment by mr-yaky** [comment]
Wow, awesome reaction @DavidSpek. So, fast! Thank you BTW.

Yes, sure, I can share my yaml files:

```
$ cat servicerolebinding.yaml envoyfilter.yaml 
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-ml-pipeline-nb-mynamespace
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: ml-pipeline-services
  subjects:
  - properties:
      source.principal: cluster.local/ns/test/default-editor
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-header
  namespace: test
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: ml-pipeline.kubeflow.svc.cluster.local:8888
          route:
            name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: true
          header:
            key: kubeflow-userid
            value: anonymous@kubeflow.org
  workloadSelector:
    labels:
      notebook-name: kale-test
```

```
$ kubectl -n test get po -l notebook-name=kale-test
NAME          READY   STATUS    RESTARTS   AGE
kale-test-0   2/2     Running   0          3d
```

Also output from Web UI Terminal session:
```
jovyan@kale-test-0:~$ kfp pipeline list
(403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 09 Nov 2020 17:30:30 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: RBAC: access denied
```

**Comment by mr-yaky** [comment]
```
$ kubectl get ns test -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner: anonymous@kubeflow.org
```

**Comment by DavidSpek** [comment]
@mr-yaky Did you create the namespace `test` yourself or is that the default namespace for the single-user kubeflow deployment? If you created it yourself, I believe what might be happening is that you are trying to authenticate with KFP which does not accept passing a namespace in single-user mode and is hardcoded to use the  default namespace of a single-user deployment (which is `kubeflow` to my knowledge).

**Comment by mr-yaky** [comment]
> @mr-yaky Did you create the namespace `test` yourself or is that the default namespace for the single-user kubeflow deployment? If you created it yourself, I believe what might be happening is that you are trying to authenticate with KFP which does not accept passing a namespace in single-user mode and is hardcoded to use the default namespace of a single-user deployment (which is `kubeflow` to my knowledge).

Well, this ns was created on initial step after first start of kubeflow and I didn't create it manually. I just set the name for ns from web UI. I don't know but maybe I can test another workaround: https://github.com/kubeflow/pipelines/issues/4440#issuecomment-713696452

we don't need RBAC and different users at all now.

**Comment by DavidSpek** [comment]
@mr-yaky Would you be able to try setting the namespace to `kubeflow` and trying with that? I would have expected the single-user deployment the default namespace rather than allowing users to set it as the reason for using namespace is to isolate multiple users from each other.

**Comment by mr-yaky** [comment]
@DavidSpek I tried to create additional ns for anonymous@kubeflow.org user by following command: 

```
curl -XPOST http://localhost:31380/api/workgroup/create

$ kubectl get ns anonymous --show-labels
NAME        STATUS   AGE   LABELS
anonymous   Active   71m   istio-injection=enabled,katib-metricscollector-injection=enabled,serving.kubeflow.org/inferenceservice=enabled
```
After creating new ns I could see it in central web ui and I choosed it added additional kale server.
And after applying `ServiceRoleBinding` for kubeflow and `EnvoyFilter` for that new ns I got the same error.
This is very weird. Also disabling Isito RBAC globally (https://github.com/kubeflow/pipelines/issues/4440#issuecomment-700759162) didn't fix the problem as well :(

**Comment by mr-yaky** [comment]
I checked kubeflow docs but couldn't see how to set `kubeflow` ns for user pipelines. Also I can't see that ns on central web ui. I'm not sure that is possible.
What do you think, should I test installation with DEX ? Maybe it will fix my problem?

**Comment by DavidSpek** [comment]
The single-user deployment relies on the namespace being `kubeflow` to my knowledge, so using the namespace `anonymous` would then cause the same issues as using the namespace `test`. I would try redeploying kubeflow in single-user mode and when prompted to create a namespace make sure it is `kubeflow`. If that fails you could deploy with DEX, which does give the option to have multiple users use the cluster in the future.

**Comment by mr-yaky** [comment]
well, I fixed already that issue with adding following to my servicerolebinding config: https://github.com/kubeflow/pipelines/issues/4440#issuecomment-726303500
@DavidSpek thank you for your support.
