### ISSUE TITLE
A rok API URL must be provided when compiling and running titanic jupyter lab

### ISSUE THREAD

**Issue by jackhawa** [kubeflow-kale/kale#21]
I have installed a fresh minikf and followed the steps outlined [here](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-minikf-kale/#3). When I compile and run the pipeline, the loaddata step fails with the message:

ValueError: A Rok API URL must be provided either via the `url' argument or the `ROK_GW_URL' environment variable.

Any idea what this is about? See below screenshot. Thanks.

![image](https://user-images.githubusercontent.com/7749809/70104160-2c2fc180-160b-11ea-993a-fee5ce84c2b0.png)

**Comment by klolos** [comment]
Hello @jackhawa !

Are you by any chance trying to run the guide inside a Vagrant box instead of the MiniKF available on Google Cloud?

I'm afraid you will not be able to complete this guide using the current MiniKF on Vagrant (v20190918.1.0), since it does not include the latest version of Rok and does not setup the required environment inside the pipeline pods to allow autosnapshotting.

If that was the case, can you please try the MiniKF available on Google Cloud instead?

**Comment by jackhawa** [comment]
Hi @klolos,

I am using MiniKF locally on my windows machine and yes it is inside a Vagrant box. 

Is there any workaround or will I have to wait for the next Rok release?
If it is the latter, when will it be?
My company only works with Azure. Will this guide work with MiniKf on Azure Cloud?

Thanks.

**Comment by jackhawa** [comment]
On a side note, I also have built custom TFX components. Will kale be able to package up my custom code in a docker container and run it on the pipeline or does kale only work with imported libraries? Thanks.

**Comment by nicklawson** [comment]
The pipeline will at least complete under this setup if you disable '_Take Rok snapshots before each step_' in the _Kale Deployment Panel_
- although this obviously negates some of the advantages of having Rok

**Comment by yaliqin** [comment]
@klolos , I met the same problem when I integrate Kale in Kubeflow which is deployed on a kubernetes cluster on GCP.  
I deployed MiniKF&Kale in my workstation with Virtualbox before. Everything works well to run the example.
Because when I switch to the kubernetes cluster on GCP, I met problems.
1, when I set up the notebook server, I add a data volume.  when I open the Kale deployment panel, I can't select "Use this notebook's volumes". So I select "create empty volume" in this panel When I run the pipeline, the error message is "ValueError: A Rok API URL must be provided either via the url' argument or the ROK_GW_URL' environment variable."
2, Then I disable the "Take Rok snapshots before each step" option, a new error comes out "Traceback (most recent call last):
  File "<string>", line 59, in <module>
  File "<string>", line 16, in loaddata
ModuleNotFoundError: No module named 'seaborn'".     But I already pip intall seaborn before I submit the pipeline and the python code itself can run successfully.

Is any instruction about the storage volume setting in the case of storage class other than rok already existing?

**Comment by frezbo** [comment]
https://github.com/kubeflow-kale/kale/issues/21#issuecomment-582336784 the option is greyed out for me and when the pipeline is run it throws the error for missing Rok url? Which image were you using?

**Comment by BennySemyonov** [comment]
same issue here, when i use minikf in gcp with default gcr.io/arrikto/jupyter-kale-py38 images.
someone has a fix?
