### ISSUE TITLE
Cannot access to google cloud bucket using pipeline 

### ISSUE THREAD

**Issue by Felihong** [kubeflow-kale/kale#31]
Hi there,

I got a permission error when I was trying to write the results to gcs bucket within a pipeline function using kale:
```
Traceback (most recent call last):
  File "<string>", line 93, in <module>
  File "<string>", line 83, in generate_data
  File "<string>", line 74, in generate_data
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/storage/client.py", line 305, in get_bucket
    bucket.reload(client=self)
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 140, in reload
    _target_object=self,
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/_http.py", line 421, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/bucket-data?projection=noAcl: Primary: /namespaces/kube.svc.id.goog with additional claims does not have storage.buckets.get access to bucket-data.
```

This feels like a lack of proper `gcp-secret`, I'm using `kubeflow 0.7 on GCP` and the `workload identity` works fine in my notebook pod. However as the pipeline component doesn't run in the same pod. 
I want to ask does kale support the ` kfp.gcp` module now? Or is there a way to set the private key as a pipeline parameter? 

Thanks in advance!

**Comment by Felihong** [comment]
Just found I need to create a google service account and bind this to the k8s service account used by the pipeline standalone deployment https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/. 
So the problem has been solved, sorry for bothering :)
