### ISSUE TITLE
'create_katib_experiment' raised an RPCError

### ISSUE THREAD

**Issue by ankita4AI** [kubeflow-kale/kale#317]
Notebook: dog-breed-classification/dog-breed-katib.ipynb
Error trail:
2021-03-02 06:02:55 run:120 [[ERROR]] [TID=gsco3qkysa] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed-katib.ipynb] RPC function 'create_katib_experiment' raised an RPCError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 95, in _launch_katib_experiment
    katib_experiment)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_inf(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e12cea07-ee1d-4b37-afc1-db50811bf099', 'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 02 Mar 2021 06:02:55 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found

I fail to understand the issue here, any thoughts would be appreciated, 
TIA

**Comment by coldtomatojuice** [comment]
this issue seems to be related to katib version
currently kale sdk send katib API with version v1alpha3
however, if kubeflow 1.2 is installed, katib API version is v1beta1 
therefore the API address for version v1alpha3 can't be found

**Comment by elikatsis** [comment]
Hi @ankita4AI 

Indeed it's what @coldtomatojuice has said, and thanks for the answer!

We have some code internally that we're testing which enables Kale to support both Katib `v1alpha3` and `v1beta1`. We will hopefully release it soon!
