### ISSUE TITLE
Unable to create katib experiment

### ISSUE THREAD

**Issue by jazzsir** [kubeflow-kale/kale#370]
I get the error message below when I run a dog-breed example

```
An RPC Error has occurred
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

Type: RPC

Method: katib.create_katib_experiment()

Code: 6 (UnhandledError)

Transaction ID: p8itcelaoc

Message: Failed to launch Katib experiment

Details: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'b776fc82-92d8-4d99-9222-b3e38bf437d4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '469019c6-6d65-4623-acbf-67967d6d6d51', 'Date': 'Mon, 13 Sep 2021 04:04:10 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```
- kale.log

```
2021-09-13 04:24:30 run:114 [[INFO]] [TID=vaydfhye0n] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed.ipynb] Executing RPC function 'create_katib_experiment(pipeline_id=694c5025-32ca-4039-a19d-31321aff05e2, version_id=4d6798c3-42f5-4a1c-9978-c403f285b544, pipeline_metadata={'autosnapshot': False, 'docker_image': 'regi.local:5000/base/kale:dog.0.1', 'experiment': {'id': 'new', 'name': 'dog-breed-katib'}, 'experiment_name': 'dog-breed-katib-tzjum', 'katib_metadata': {'parameters': [{'feasibleSpace': {'max': '300', 'min': '200', 'step': '10'}, 'name': 'nodes_number', 'parameterType': 'int'}, {'feasibleSpace': {'max': '0.0009', 'min': '0.00009', 'step': '0.0001'}, 'name': 'learning_rate', 'parameterType': 'double'}], 'objective': {'additionalMetricNames': [], 'goal': 90, 'objectiveMetricName': 'test-accuracy-resnet', 'type': 'maximize'}, 'algorithm': {'algorithmName': 'random', 'algorithmSettings': [{'name': 'random_state', 'value': '10'}]}, 'maxTrialCount': 200, 'maxFailedTrialCount': 3, 'parallelTrialCount': 1}, 'katib_run': True, 'pipeline_description': '', 'pipeline_name': 'dog-breed', 'snapshot_volumes': False, 'steps_defaults': ['label:access-ml-pipeline:true'], 'volume_access_mode': 'rwm', 'volumes': [{'annotations': [], 'mount_point': '/data', 'name': 'dog-pvc', 'size': 1, 'size_type': 'Gi', 'snapshot': False, 'snapshot_name': '', 'type': 'pvc'}]}, output_path=/home/jovyan/kale/examples/dog-breed-classification)'
2021-09-13 04:24:30 katib:184 [[INFO]] [TID=vaydfhye0n] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed.ipynb] Saving Katib experiment definition at /home/jovyan/kale/examples/dog-breed-classification/dog-breed-katib-tzjum.katib.yaml
2021-09-13 04:24:30 katib:92 [[DEBUG]] [TID=vaydfhye0n] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed.ipynb] Launching Katib Experiment 'dog-breed-katib-tzjum'...
2021-09-13 04:24:30 katib:98 [[ERROR]] [TID=vaydfhye0n] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed.ipynb] Failed to launch Katib experiment
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 96, in _launch_katib_experiment
    katib_experiment)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'b776fc82-92d8-4d99-9222-b3e38bf437d4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '469019c6-6d65-4623-acbf-67967d6d6d51', 'Date': 'Mon, 13 Sep 2021 04:24:30 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found


2021-09-13 04:24:30 run:120 [[ERROR]] [TID=vaydfhye0n] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed.ipynb] RPC function 'create_katib_experiment' raised an RPCError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 96, in _launch_katib_experiment
    katib_experiment)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'b776fc82-92d8-4d99-9222-b3e38bf437d4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '469019c6-6d65-4623-acbf-67967d6d6d51', 'Date': 'Mon, 13 Sep 2021 04:24:30 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/run.py", line 116, in run
    result = func(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 189, in create_katib_experiment
    _launch_katib_experiment(request, katib_experiment, namespace)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 100, in _launch_katib_experiment
    details=str(e), trans_id=request.trans_id)
kale.rpc.errors.RPCUnhandledError

```

**Versions**
Kubeflow: 1.3 (katib-controller : 0.11.0, KFP 1.6)
Kubeflow-kale
- Version: 0.7.0, 0.6.0
- Jupyter image: gcr.io/arrikto/jupyter-kale:6f87224e-9f74f267
- base image: gcr.io/arrikto/jupyter-kale@sha256:a103ad9a9c6af49989a89d6febe957ff5c67ebc6284af31845c27d67fedcc1ba including additional packages

**Comment by jazzsir** [comment]
It was a version issue, I created v1alpha3 but the version was deprecated in katib-controller 0.11.0.
How can I create a v1beta1 experiment through kubeflow-kale ?

**Comment by jazzsir** [comment]
I found the Dockerfile here
