### ISSUE TITLE
Facing issue in kale while executing program

### ISSUE THREAD

**Issue by Roma110** [kubeflow-kale/kale#415]
Hi All,
  We have installed kale 0.7.0 and trying to run basic kale example in pipeline and facing below issue:
 Error:
`Traceback (most recent call last):
  File "/tmp/tmp.hsdiC1bhPS", line 27, in <module>
    _outputs = singlestep(**_parsed_args)
  File "/tmp/tmp.hsdiC1bhPS", line 16, in singlestep
    _kale_html_artifact = _kale_run_code(_kale_blocks)
  File "/usr/local/lib/python3.6/dist-packages/kale/common/jputils.py", line 285, in run_code
    ep.preprocess(notebook, resources, km=km)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 479, in _poll_for_reply
    if msg['parent_header'].get('msg_id') == msg_id:
TypeError: 'coroutine' object is not subscriptable
sys:1: RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
`
![image](https://user-images.githubusercontent.com/28138074/168584057-17dc89a7-9295-4f09-9cfc-59a23f0b29af.png)

**Config Details**:
JupyterLab  v2.3.2
kale  0.7.0 

Could someone please look into this issue?

**Comment by vitobotta** [comment]
Having the same error. Did you find a solution?

**Comment by wpalex2023** [comment]
I have got the same error
