### ISSUE TITLE
Getting Started fails: TypeError: code() takes at least 14 arguments (13 given)

### ISSUE THREAD

**Issue by ayushkovskiy** [kubeflow-kale/kale#73]
Hi, 
I'm trying to run an example from Getting Started from README and it seems there's a bug in code:
```
$ pip install kubeflow-kale
...
$ wget https://raw.githubusercontent.com/kubeflow-kale/examples/master/titanic-ml-dataset/titanic_dataset_ml.ipynb
...

$ kale --nb titanic_dataset_ml.ipynb
03-03 22:35 | kubeflow-kale |  INFO: Pipeline code saved at titanic-ml-dq7ht.kale.py
Traceback (most recent call last):
  File "/home/ay/venv/bin/kale", line 10, in <module>
    sys.exit(main())
  File "/home/ay/venv/lib/python3.8/site-packages/kale/command_line.py", line 65, in main
    pipeline_package_path = kfp_utils.compile_pipeline(script_path, kale.pipeline_metadata['pipeline_name'])
  File "/home/ay/venv/lib/python3.8/site-packages/kale/utils/kfp_utils.py", line 52, in compile_pipeline
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpbaqy973a/pipeline_code.py", line 903, in <module>
    loaddata_op = comp.func_to_container_op(loaddata)
  File "/home/ay/venv/lib/python3.8/site-packages/kfp/components/_python_op.py", line 694, in func_to_container_op
    return _create_task_factory_from_component_spec(component_spec)
  File "/home/ay/venv/lib/python3.8/site-packages/kfp/components/_components.py", line 276, in _create_task_factory_from_component_spec
    task_factory = _dynamic.create_function_from_parameters(
  File "/home/ay/venv/lib/python3.8/site-packages/kfp/components/_dynamic.py", line 47, in create_function_from_parameters
    modified_code = types.CodeType(
TypeError: code() takes at least 14 arguments (13 given)

$ python --version
Python 3.8.1

$ pip freeze | grep kale
kubeflow-kale==0.4.0

```

**Comment by ayushkovskiy** [comment]
Unfortunately, it fails cifar example too :( 
https://github.com/kubeflow-kale/examples/blob/master/pytorch-classification/cifar10_classification.ipynb

**Comment by elikatsis** [comment]
Hello!

What's the output of `pip freeze | grep kfp`?
