### ISSUE TITLE
Resource conversion Error while executing Kale Pipeline

### ISSUE THREAD

**Issue by Byest** [kubeflow-kale/kale#91]
Hey all, hope all is well~~
So after using the Kale Deployment Panel to "Compile and Run" a Jupyter notebook, I get this error while the Pipeline is executing.

<img width="606" alt="Screen Shot 2020-04-02 at 11 55 16 AM" src="https://user-images.githubusercontent.com/6002936/78270474-e01d5c80-74d8-11ea-88f9-b000b6a4b957.png">

```
Saving general object: input_fn
Traceback (most recent call last):
  File "<string>", line 886, in <module>
  File "<string>", line 870, in build_model
  File "/usr/local/lib/python3.6/dist-packages/kale/marshal/dispatchers.py", line 63, in __call__
    return self.dispatch(s)(s, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/marshal/resource_save.py", line 17, in resource_all
    dill.dump(o, f)
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 445, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 1413, in save_function
    obj.__dict__, fkwdefaults), obj=obj)
  File "/usr/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 1147, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "/usr/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
  File "/home/jovyan/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 884, in __reduce__
    return convert_to_tensor, (self._numpy(),)
**ValueError: Cannot convert a Tensor of dtype resource to a NumPy array.**
```

I believe the first line number is referencing pipeline.yaml?
```
 883             if "epoch_cnt" in locals(): 
 884                 _kale_resource_save(epoch_cnt, os.path.join( 
 885                     _kale_data_directory, "epoch_cnt")) 
 886             else: 
 887                 print("_kale_resource_save: `epoch_cnt` not found.")
```

Notes
- The code does execute properly in jupyter notebook
- epoch_cnt is just an integer "epoch_cnt = 0" defined in a previous step of the pipeline. I've removed most usages of it, but no luck
- Tried combining all the jupyter blocks into one block, and still get this problem.
- Possible causes (grasping at straws):
    - tf.lookup.StaticVocabularyTable(tf.lookup.KeyValueTensorInitializer(
    - tf.data.experimental.make_csv_dataset(...) in input_fn()

Been stuck on this forever. Any help would be greatly appreciated. Thanks~~

**Comment by StefanoFioravanzo** [comment]
Hey @Byest I see in the first stacktrace that Kale il trying to `Saving general object: input_fn`. So this means that you step `build-model` is declaring that object that is used by a child step. Kale detects this dependency and tried to marshal (i.e. save to disk) that object. 

Kale can support special type of objects that cannot be marshalled using pickle. What type of object is it? Also, what version of kale are you running?

**Comment by Byest** [comment]
Hey @StefanoFioravanzo,
Thanks for the feedback~~ Kale version is 0.4.0~ This is the object that is referenced in input_fn()
```
vocab_table = tf.lookup.StaticVocabularyTable(
      tf.lookup.KeyValueTensorInitializer(
          [""] + vocab, range(0,vocab_rows_cnt + 1), key_dtype=tf.string, value_dtype=tf.int64), 
      num_oov_buckets)
```
I think the problem was that it was declared at the global level. I moved that into the input_fn itself, and that seems to have fixed it, since it doesn't try to save it as a resource then(?). In any case, the pipeline is running without problems now.

This is only somewhat related, but mind if I ask what files these line numbers reference? It doesn't seem to match up to pipeline.yaml or the *kale.py files, unless I'm mistaken.
```
  File "<string>", line 886, in <module>
  File "<string>", line 870, in build_model
```

Thanks again, we really appreciate the work you guys are doing. Kale is gonna play such an integral part in our end-to-end ML pipeline~~ :thumbsup:

**Comment by elikatsis** [comment]
>This is only somewhat related, but mind if I ask what files these line numbers reference? It doesn't seem to match up to pipeline.yaml or the *kale.py files, unless I'm mistaken.
>
>```
>  File "<string>", line 886, in <module>
>  File "<string>", line 870, in build_model
>```

These refer to KFP-generated lines of code[1] wrapping each piece of your code (actually your code wrapped in a function with some Kale additions).

It all comes down to calling functions. `build_model` is that function which your step (`build-model`) runs.
Then, `self.dispatch(...)` is called by some code Kale injects to ensure your variables get passed from step to step, so it essentially lives in `build_model` function.

---

[1]: The KFP generated code is actually
```
python3 -c "...inline code..." ...args...
```
where that inline code has this form
```python3
def my_func(...args...):
    ...your code + Kale code...

...argparse...
outputs = my_func(...args...)

...some extras...
```

So the Exception occurs in `<module>` which refers to the inline code, `my_func` (which is your code + Kale code), etc..

---

We really appreciate your kind words! :smile:
